#!/bin/sh

IMAGE=scipy-notebook

docker run -it -p 8888:8888 --rm --name lab-"$IMAGE" \
  -v "$PWD":/home/jovyan/work \
  --ipc=host \
  jupyter/"$IMAGE":latest jupyter lab \
  --ip=0.0.0.0 \
  --no-browser \
  --allow-root \
  --NotebookApp.token=\
  --notebook-dir=/home/jovyan/work
