#!/bin/sh

IMAGE=deepo

docker run -it -p 8888:8888 --rm --name lab-"$IMAGE" \
  -v "$PWD":/home/jovyan/work \
  --ipc=host \
  ufoym/"$IMAGE":all-py36-cpu jupyter notebook \
  --ip=0.0.0.0 \
  --no-browser \
  --allow-root \
  --NotebookApp.token=\
  --notebook-dir=/home/jovyan/work
